M48
; DRILL file {KiCad (7.0.0)} date Sat Apr 15 14:38:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-15T14:38:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0551
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X1.5Y-1.0
X1.5Y-1.4
X1.6Y-1.0
X1.6Y-1.4
T2
X1.6Y-0.7
X1.6Y-1.7
X2.6Y-0.7
X2.6Y-1.7
T3
X2.1Y-1.2
X2.2969Y-1.2
T0
M30
